### PR TITLE
Deathknight update for 7.2.5 patch.

### PR DESCRIPTION
**Pull request by Cluuey**
Required level has changed for a few abilities.
Added bar colours, frost still needs a tweak but works.

### CODE REVIEW

**Comment by Cluuey** [comment]
Server came up, added more colours for Frost.

**Comment by Brusalk** [comment]
Thanks for all the PRs @Cluuey! They look awesome. I hope everyone will enjoy having the differentiated colors now :)

One minor thing is that it looks like your editor is configured to use hard tab-characters (\t), instead of the two-space indentation that is standard for EH. Do you think you could fix the indentation in your PRs to use two spaces for indentation across the board?

**Comment by Cluuey** [comment]
oh, that's probably because I've been working from the  <class>_my_config files for lots of these.
I remember noticing that if you wanted to add a new line and press `Enter` at the end of a line indented by four spaces Notepad++ would automatically start the new line with a `Tab`.
I remember that drove me mad because I have the _show white spaces_ option on.

I've been up 30 hours now doing these, I can't remove them now. I'm likely to make a mistake. :-(

**Comment by Cluuey** [comment]
hhmmm, just noticed something isn't working as expected, not a show stopper though.

`debuff = {{196782,6}, {191587,3}},`
The first part of the spell ability spreads the plague debuff (second spell id with a tick of 3) around, it does it for six seconds so I thought I could track both. However there are no tick markers showing up.
What did I do wrong?

**Pull request merged**
